name: Bazel

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  MacOS:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: bazelisk test //Tests:UnitTests --test_env=PROJECT_ROOT=$(bazelisk info workspace)
  Linux:
    strategy:
      matrix:
        tag: ['5.5']
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.
      - name: Setup Bazel
        if: always()
        run: go get github.com/bazelbuild/bazelisk
        shell: bash
      - run: bazelisk test //Tests:UnitTests --test_env=PROJECT_ROOT=$(bazelisk info workspace)
